# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 21:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date of glory')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.OurUser')),
            ],
        ),
    ]
