# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guinea_pig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
