# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guinea_pig', '0006_auto_20160520_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.UserProfile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='game',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
