# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guinea_pig', '0007_auto_20160523_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date of glory')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.UserProfile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guinea_pig.Game')),
            ],
        ),
    ]
