# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guinea_pig', '0008_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='author',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='record',
            name='game_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of glory'),
        ),
    ]
